const express = require("express");
const router = express.Router();

const authMiddleware = require("../middleware/authMiddleware");
const validate = require("../middleware/validationMiddleware");

const {
    sosValidation
} = require("../validators/sosValidator");

const {
    createSOSEvent,
    getSOSHistory
} = require("../controllers/sosController");

/**
 * @swagger
 * tags:
 *   name: SOS
 *   description: Emergency SOS APIs
 */

/**
 * @swagger
 * /api/sos/send:
 *   post:
 *     summary: Send an SOS alert
 *     description: Creates an emergency SOS event with the device's location.
 *     tags: [SOS]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - deviceId
 *               - latitude
 *               - longitude
 *             properties:
 *               deviceId:
 *                 type: string
 *                 example: 6a5a7d58a7febf50641e0237
 *               latitude:
 *                 type: number
 *                 example: 12.9716
 *               longitude:
 *                 type: number
 *                 example: 77.5946
 *               message:
 *                 type: string
 *                 example: Emergency! Please help.
 *     responses:
 *       201:
 *         description: SOS alert sent successfully
 *       400:
 *         description: Validation error
 *       401:
 *         description: Unauthorized
 */
router.post(
    "/send",
    authMiddleware,
    sosValidation,
    validate,
    createSOSEvent
);

/**
 * @swagger
 * /api/sos/history/{deviceId}:
 *   get:
 *     summary: Get SOS history
 *     description: Retrieve all SOS alerts generated by a device.
 *     tags: [SOS]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: deviceId
 *         required: true
 *         schema:
 *           type: string
 *         example: 6a5a7d58a7febf50641e0237
 *     responses:
 *       200:
 *         description: SOS history retrieved successfully
 *       404:
 *         description: Device not found
 *       401:
 *         description: Unauthorized
 */
router.get(
    "/history/:deviceId",
    authMiddleware,
    getSOSHistory
);

module.exports = router;